#:import AnimatedAsyncImage utils.image_utils.AnimatedAsyncImage
#:set color1 "#DD7835"

<ScreenEmentaUtilizador>:
    ProdutoEmentaWidget:
        BoxLayout:
            orientation: "vertical"
            MDLabel:
                id: nome
                hint_text: "Produto"
                text: ""
            MDLabel:
                id: descricao_curta
                hint_text: "Descrição"
                text: ""